default_config:
recorder: 
  db_url: !secret db_url
#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml

# allow for the fact we have a reverse proxy in the stack and 
# leave the default address flexible enough for any docker private range
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
